export function getEls() {
  return {
    dimInput: document.getElementById("dimInput"),
    resizeBtn: document.getElementById("resizeBtn"),
    textInput: document.getElementById("textInput"),
    typeInput: document.getElementById("typeInput"),
    tokenInput: document.getElementById("tokenInput"),
    addBtn: document.getElementById("addBtn"),
    newBtn: document.getElementById("newBtn"),
    list: document.getElementById("list"),
    searchInput: document.getElementById("searchInput"),
    selectedMeta: document.getElementById("selectedMeta"),
    vectorArea: document.getElementById("vectorArea"),
    randomBtn: document.getElementById("randomBtn"),
    normalizeBtn: document.getElementById("normalizeBtn"),
    saveVecBtn: document.getElementById("saveVecBtn"),
    neighbors: document.getElementById("neighbors"),
    exportBtn: document.getElementById("exportBtn"),
    importBtn: document.getElementById("importBtn"),
    importFiles: document.getElementById("importFiles"),
    importHint: document.getElementById("importHint"),
    jsonArea: document.getElementById("jsonArea"),
    pcaBtn: document.getElementById("pcaBtn"),
    centerBtn: document.getElementById("centerBtn"),
    resetViewBtn: document.getElementById("resetViewBtn"),
    seedDemoBtn: document.getElementById("seedDemoBtn"),
    clearBtn: document.getElementById("clearBtn"),
    canvas: document.getElementById("plot"),
  };
}
